---
Gemfile:
  optional:
    ':development':
      - gem: 'puppet_litmus'

spec/spec_helper.rb:
  mock_with: ':rspec'

.travis.yml:
  use_litmus: true
  litmus:
    provision_list: [travis_deb, travis_ub_6, travis_el6, travis_el7, travis_el8]
    puppet_collection: [puppet5, puppet6, puppet7]
